name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: gajalakhsmi98/github-actions-issue-to-work-item@master
        env:
          ado_token: "nyeudjilttp5ylssqmygqj4c3jkt225c7g5qknnr7h4x3ejxrh3q"
          github_token: "dd5469d693454d4b7e90d4ef50601b815607a75a"
          ado_organization: "gajanarayanan"
          ado_project: "Azure git demo"
          ado_area_path: "optional_area_path\\optional_area_path"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
